/*
-----------------------------------------------------------------------------
Filename:    scAnimationTest.h
-----------------------------------------------------------------------------


This source file is generated by the
   ___                   _              __    __ _                  _ 
  /___\__ _ _ __ ___    /_\  _ __  _ __/ / /\ \ (_)______ _ _ __ __| |
 //  // _` | '__/ _ \  //_\\| '_ \| '_ \ \/  \/ / |_  / _` | '__/ _` |
/ \_// (_| | | |  __/ /  _  \ |_) | |_) \  /\  /| |/ / (_| | | | (_| |
\___/ \__, |_|  \___| \_/ \_/ .__/| .__/ \/  \/ |_/___\__,_|_|  \__,_|
      |___/                 |_|   |_|                                 
      Ogre 1.7.x Application Wizard for VC10 (July 2011)
      http://code.google.com/p/ogreappwizards/
-----------------------------------------------------------------------------
*/
#ifndef __scAnimationTest_h_
#define __scAnimationTest_h_

#include "BaseApplication.h"
#include "../res/resource.h"

#include "scTimeLineManager.h"
#include "MyGUI.h"
#include "MyGUI_OgrePlatform.h"

class scAnimationTest : public BaseApplication
{
public:
    scAnimationTest(void);
    virtual ~scAnimationTest(void);

protected:
    virtual void createScene(void);

	virtual bool frameRenderingQueued( const Ogre::FrameEvent& evt );

	virtual bool keyPressed( const OIS::KeyEvent &arg );

private:
	scTimeLineManager* mTimeLineManager;
	MyGUI::Gui* mGui;
	MyGUI::OgrePlatform* mPlatform;

};

#endif // #ifndef __scAnimationTest_h_
